[package]
name = "zoneplate"
version = "0.1.0"
description = "Example Rust/WASM for next.js with hot module replacement"
authors = ["Daniel Lauzon","The wasm-bindgen Developers"]

edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.67"
lazy_static = "1.4.0"

[dependencies.web-sys]
version = "0.3.4"
features = [
  'ImageData',
  'CanvasRenderingContext2d',
]
